
const demoFrame = document.getElementById('demo-frame');
const vibeModal = document.getElementById('vibeModal');
const demoPages = { home: `<div class="demo-page" data-page="home"><div class="demo-header"><strong>Twist</strong><div class="demo-avatar" style="background-image:url('assets/vector_profile.svg')"></div></div><div class="swipe-card"><div class="profile-pic" style="background-image:url('assets/vector_profile.svg')"></div><strong>Sam, 25</strong><div class="tags"><span style="background:linear-gradient(90deg,#00ffd5,#9d00ff);padding:6px 8px;border-radius:8px;color:#000;font-weight:800">💚 Vert Amnesia</span></div><p class="intent">Vibe chill • 2,1 km</p><div class="swipe-actions"><div class="action" onclick="swipe('no')">❌</div><div class="action" onclick="swipe('yes')">💚</div></div></div></div>`, create: `<div class="demo-page" data-page="create"><div class="demo-header"><strong>Créer profil</strong></div><div style="margin-top:12px;text-align:left;width:100%"><label>Pseudo</label><input placeholder="Ton pseudo" style="width:100%;padding:10px;border-radius:8px;margin-top:8px;background:transparent;border:1px solid rgba(255,255,255,0.04);color:#fff"><label style="margin-top:12px;display:block">Choisis une vibe</label><select style="width:100%;padding:10px;border-radius:8px;margin-top:8px;background:transparent;border:1px solid rgba(255,255,255,0.04);color:#fff"><option>💚 Vert Amnesia</option><option>💛 Lemon Haze</option><option>❤️ Strawberry Haze</option><option>💙 Purple Haze</option></select></div></div>`, swipe: `<div class="demo-page" data-page="swipe"><div class="demo-header"><strong>Swipe</strong></div><div class="swipe-card"><div class="profile-pic" style="background-image:url('assets/vector_profile.svg')"></div><strong>Ana, 23</strong><div class="tags"><span style="background:linear-gradient(90deg,#00ffd5,#9d00ff);padding:6px 8px;border-radius:8px;color:#000;font-weight:800">💛 Lemon Haze</span></div><p class="intent">Sortie plage • 4,5 km</p><div class="swipe-actions"><div class="action" onclick="swipe('no')">❌</div><div class="action" onclick="swipe('yes')">💚</div></div></div></div>`, chat: `<div class="demo-page" data-page="chat"><div class="demo-header"><strong>Chat</strong></div><div style="width:100%;height:100%;display:flex;flex-direction:column;padding:12px"><div class="chat-log" id="chatLog"><div class="msg-bubble">Salut — tu fais quoi ce soir ?</div><div class="msg-bubble me">J'suis chaud pour une session courte ✌️</div></div><div style="display:flex;gap:8px;margin-top:8px"><input id="chatInput" placeholder="Écris un message..." style="flex:1;padding:10px;border-radius:8px;border:1px solid rgba(255,255,255,0.04);background:transparent;color:#fff"><button class="small" onclick="sendMsg()">Envoyer</button></div></div></div>` };
function demoNav(page){ demoFrame.innerHTML = demoPages[page]; if(page==='chat'){ setTimeout(()=>{ const cl = document.getElementById('chatLog'); if(cl) cl.scrollTop = cl.scrollHeight; },50); } }
function openDemo(){ document.querySelector('#demo').scrollIntoView({behavior:'smooth'}); demoNav('home'); }
function swipe(dir){ const el = document.querySelector('.swipe-card'); if(!el) return; el.style.transform = dir==='yes' ? 'translateX(120px) rotate(6deg)' : 'translateX(-120px) rotate(-6deg)'; el.style.transition = 'transform 300ms ease'; setTimeout(()=>{ demoNav('swipe'); },350); }
function sendMsg(){ const input = document.getElementById('chatInput'); const val = input.value.trim(); if(!val) return; const log = document.getElementById('chatLog'); const div = document.createElement('div'); div.className = 'msg-bubble me'; div.innerText = val; log.appendChild(div); input.value=''; log.scrollTop = log.scrollHeight; }
function submitForm(e){ e.preventDefault(); document.getElementById('msg').innerText = "Merci — tu es inscrit(e) à la liste d'attente ! On t’envoie un mail bientôt."; document.getElementById('betaForm').reset(); }
function openVibe(v){ const modal = document.getElementById('vibeModal'); let title='', desc='', color=''; if(v==='green'){ title='💚 Vert — Amnesia'; desc='Chill, séries, musique : cherche des potes pour se poser.'; color='var(--green)'; } if(v==='yellow'){ title='💛 Jaune — Lemon Haze'; desc='Soleil & sorties : organise des plans en journée.'; color='var(--yellow)'; } if(v==='red'){ title='❤️ Rouge — Strawberry Haze'; desc='Énergie & duo : recherche d\'une connexion plus intime.'; color='var(--red)'; } if(v==='blue'){ title='💙 Bleu — Purple Haze'; desc='Nightlife & teuf : pour les oiseaux de la nuit.'; color='var(--blue)'; } modal.innerHTML = `<div class="modal-card" style="border-top:6px solid ${color}"><h3>${title}</h3><p>${desc}</p><div style="margin-top:12px;text-align:right"><button class="small" onclick="closeVibe()">Fermer</button></div></div>`; modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); }
function closeVibe(){ const modal=document.getElementById('vibeModal'); modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); modal.innerHTML=''; }
document.addEventListener('DOMContentLoaded',()=>{ const obs = new IntersectionObserver((entries)=>{ entries.forEach(e=>{ if(e.isIntersecting) e.target.classList.add('in-view'); }); }, {threshold:0.15}); document.querySelectorAll('.fade-up').forEach(el=>obs.observe(el)); });
